// GENERATED by `make contract` (api/app/contract.py) from
// docs/contract/motion-spec.schema.json. DO NOT EDIT BY HAND.
// Geometry is CSS px, times are integer ms, every value is an estimate.

/* ---------- named literal types ---------- */

export type InteractionType = "hover" | "click" | "press" | "expand_collapse" | "dropdown" | "modal" | "unknown" | "continuous" | "drag";
export type TypeSource = "heuristic" | "interpreter";
export type Pattern = "card" | "button" | "menu" | "accordion" | "modal" | "generic" | "marquee" | "carousel";
export type TriggerKind = "pointer_enter" | "click" | "unknown" | "autoplay" | "drag";
export type ReverseTriggerKind = "pointer_leave" | "click" | "none" | "unknown";
export type Direction = "forward" | "forward_reverse" | "round_trip" | "continuous";
export type ElementKind = "transform" | "photometric" | "appear" | "disappear" | "backdrop" | "resize" | "content_change" | "scroller";
export type Role = "card" | "button" | "image" | "icon" | "text" | "title" | "label" | "container" | "dropdown_menu" | "menu_item" | "modal_panel" | "backdrop" | "list_item" | "link" | "input" | "badge" | "accordion_panel" | "other" | "scroller";
export type LabelSource = "interpreter" | "heuristic";
export type SegmentId = "fwd" | "rev" | "rt_in" | "rt_out";
export type SegmentKind = "forward" | "reverse";
export type Property = "translateX" | "translateY" | "scale" | "scaleX" | "scaleY" | "opacity" | "color" | "background-color" | "box-shadow" | "border-radius" | "height" | "content";
export type CssEasingKeyword = "linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out";
export type EasingFamily = "linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out" | "overshoot";
export type ConfidenceBand = "high" | "medium" | "low";
export type RelationshipKind = "simultaneous" | "sequential" | "stagger" | "delayed";
export type CursorEventKind = "enter" | "leave" | "stationary" | "move_start";
export type InterpreterProvider = "claude_cli" | "openai_compat" | "none";
export type InterpretationStatus = "ok" | "fallback" | "timeout" | "error" | "disabled";
export type PixelRatio = 1 | 2 | 3;
export type PixelRatioSource = "user" | "auto";
export type WarningSeverity = "info" | "warn";
export type WarningCode = "pixel_ratio_assumed" | "timestamps_estimated" | "vfr_source" | "cursor_not_visible" | "extra_segments_ignored" | "elements_truncated" | "short_stable_state" | "not_settled" | "rotation_detected" | "interpretation_fallback" | "interpretation_disagrees" | "low_fps_source" | "preview_unavailable" | "reverse_not_recorded" | "frames_subsampled" | "ambient_motion_masked" | "extra_scrollers_ignored" | "tracking_degraded" | "loop_period_not_observed";
export type SchemaVersion = "0.1" | "0.2";
export type SpecMode = "transition" | "continuous";
export type Axis = "x" | "y";
export type AutoplayDirection = "left" | "right" | "up" | "down";
export type PhaseKind = "autoplay" | "decelerate" | "paused" | "drag" | "inertia" | "snap" | "stop" | "resume" | "unknown";
export type PhaseEvidence = "velocity" | "cursor" | "velocity+cursor";
export type PauseTrigger = "hover" | "press" | "unknown";
export type InertiaModel = "exponential" | "tween";
export type SnapKind = "grid" | "abrupt_ambiguous";
export type PixelRatioOption = "auto" | "1" | "2" | "3";
export type KeyframeKind = "state_a" | "state_b" | "mid_25" | "mid_50" | "mid_75" | "annotated_a" | "annotated_b" | "element" | "phase";
export type UserRole = "admin" | "user";

/** Animated value; `kind` is fixed per property (see PROPERTY_VALUE_KIND). */
export type Value = PxValue | RatioValue | ColorValue | ShadowValue | TextValue;

/* ---------- models ---------- */

/** One account as seen by an admin. */
export interface AdminUser {
  id: string;
  username: string;
  role: UserRole;
  is_active: boolean;
  must_change_password: boolean;
  created_at: string;
  updated_at: string;
  last_login_at: string | null;
  job_count: number;
}

/** `GET /api/admin/users`: every account, sorted by username (no pagination). */
export interface AdminUserList {
  items: AdminUser[];
}

export interface Artifacts {
  /** H.264 preview; null if the transcode failed. */
  video_url: string | null;
  keyframes: KeyframeArtifact[];
}

/** `GET /api/auth/status` (public). `setup_required`: no admin exists yet. */
export interface AuthStatus {
  setup_required: boolean;
}

/** Constant-velocity autoplay before any interaction. */
export interface Autoplay {
  direction: AutoplayDirection;
  /** |velocity|, CSS px/s (> 0). */
  speed_px_s: MeasuredNumber;
  /** Signed velocity; same magnitude as speed_px_s. */
  velocity_px_s: number;
  easing: "linear";
  loop: LoopInfo;
}

/** What the generators print; each value aggregated over phase instances. null = not seen. */
export interface Behavior {
  pause: PauseBehavior | null;
  drag: DragBehavior | null;
  inertia: InertiaBehavior | null;
  snap: SnapBehavior | null;
  resume: ResumeBehavior | null;
}

/** Axis-aligned rectangle in CSS px, full-frame coordinates (x, y = top-left). */
export interface Box {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * Cards scale with their on-screen distance from the scroller centre (a position-driven
 * transform updated every frame; PLAN-continuous P2c).
 *
 * `scale(d) = 1 + (scale_at_reference - 1) · (d / reference_distance_px)²` where `d` is
 * the distance (CSS px, along the axis) of a card's centre from the scroller centre: 1 at the
 * centre, so the card element box, `pitch_px` and `gap_px` describe the card at the
 * centre. `reference_distance_px` is the farthest whole card measured (the curve beyond is
 * an extrapolation). The cards stay packed — the gaps keep their size — so neighbours move
 * apart as they grow.
 *
 * Speeds and displacements in the `continuous` section are on-screen values; on average over
 * the scroller the content is magnified `mean_scale` times (`1 + (scale_at_reference - 1)
 * · (half / reference_distance_px)² / 3`, half = half the region length along the axis),
 * so an unscaled track moves at `speed / mean_scale`. Stored so outputs can quote it.
 */
export interface CardScale {
  model: "quadratic";
  origin: "scroller_center";
  /** Farthest measured card-centre distance from the scroller centre. */
  reference_distance_px: number;
  /** Card scale at reference_distance_px. */
  scale_at_reference: number;
  /** Mean on-screen magnification over the scroller (speed conversion). */
  mean_scale: number;
  confidence: Confidence;
}

/** `POST /api/auth/password` body. The policy is checked in code (`weak_password`). */
export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}

/** Solid color (color, background-color). */
export interface ColorValue {
  kind: "color";
  /** Uppercase #RRGGBB. */
  color: string;
}

/** A 0..1 score plus its band. `band` must equal `band_for(value)`. */
export interface Confidence {
  value: number;
  band: ConfidenceBand;
}

/** `x(t) = x0 + v t` (autoplay). */
export interface ConstantFit {
  model: "constant";
  velocity_px_s: MeasuredNumber;
}

/** The analysed scroller (`mode == "continuous"` only). */
export interface ContinuousMotion {
  /** MotionElement with kind "scroller". */
  element_id: string;
  axis: Axis;
  /** Scroller viewport, CSS px. */
  region: Box;
  region_confidence: Confidence;
  sign_convention: "positive = content moves right (x) / down (y)";
  /** null = no autoplay before interaction. */
  autoplay: Autoplay | null;
  /** Card spacing (card + gap) if observed. */
  pitch_px: MeasuredNumber | null;
  /** Gap between cards if observed (PLAN-continuous §13). */
  gap_px: MeasuredNumber | null;
  /** Cards scale with their distance from the scroller centre. Omitted when the cards were rigid or not measured. */
  card_scale?: CardScale | null;
  phases: Phase[];
  behavior: Behavior;
  /** Analysed span (= interaction.total_duration_ms.forward). */
  span_ms: Span;
  /** [t_ms, v_px_s, pos_px, quality] for the velocity chart. Excluded from the JSON export. */
  samples: [number, number, number, number][];
}

/** `POST /api/admin/users` body. The username is stripped + lowercased, then validated. */
export interface CreateUserRequest {
  username: string;
  role?: UserRole;
}

export interface Cursor {
  visible: boolean;
  confidence: number;
  events: CursorEvent[];
}

export interface CursorEvent {
  /** Milliseconds. */
  t_ms: number;
  kind: CursorEventKind;
  element_id: string | null;
}

export interface DragBehavior {
  /** Number of drag phases. */
  count: number;
  /** null = no cursor visible to compare. */
  follows_pointer: boolean | null;
  /** Content / pointer velocity. */
  pointer_ratio: MeasuredNumber | null;
  peak_speed_px_s: MeasuredNumber;
}

/** Fitted timing function. `keyword` is set only when the fit *is* a CSS keyword curve. */
export interface Easing {
  keyword: CssEasingKeyword | null;
  /** x1, y1, x2, y2 */
  cubic_bezier: [number, number, number, number];
  /** Closest named candidate (PLAN Appendix B). */
  nearest_named: string;
  family: EasingFamily;
  /** Progress RMSE of the fit (0..1 progress units). */
  rmse: number;
  flags: "overshoot"[];
}

/**
 * Non-animated element properties (low confidence heuristics), measured in state A.
 *
 * The appearance values (PLAN-continuous §13) are optional and omitted from the JSON when not
 * measured: `background_color` (element fill), `text_color` (text-like elements only) and
 * `font_size_px` (rough estimate from the text line height; confidence at most medium).
 */
export interface ElementStatic {
  border_radius_px: MeasuredNumber | null;
  shadow: MeasuredShadow | null;
  background_color?: MeasuredColor | null;
  text_color?: MeasuredColor | null;
  font_size_px?: MeasuredNumber | null;
}

/** Every non-2xx JSON response: `{"error": {"code", "message"}}`. */
export interface ErrorBody {
  error: ErrorDetail;
}

/** Closed set of error codes shared with the frontend (`web/lib/types.ts`). */
export type ErrorCode = "unsupported_format" | "file_too_large" | "too_long" | "too_short" | "decode_failed" | "invalid_request" | "no_motion_detected" | "unsupported_motion" | "no_stable_state" | "continuous_motion_unsupported" | "internal_error" | "interrupted" | "not_found" | "not_ready" | "already_running" | "unauthenticated" | "invalid_credentials" | "account_disabled" | "forbidden" | "password_change_required" | "origin_not_allowed" | "too_many_attempts" | "setup_required" | "last_admin" | "self_action_forbidden" | "username_taken" | "weak_password" | "current_password_incorrect";

export interface ErrorDetail {
  code: ErrorCode;
  message: string;
}

/** Inertia: `v(t) = v_inf + (v0 - v_inf) e^(-t/tau)`, fitted in the position domain. */
export interface ExponentialFit {
  model: "exponential";
  tau_ms: MeasuredNumber;
  /** Release velocity (signed). */
  v0_px_s: MeasuredNumber;
  /** Asymptotic velocity: 0 or the autoplay velocity. */
  v_inf_px_s: number;
  /** Speed (|v| of the decay) at which the content was observed to come to rest; the momentum is dropped below it. Omitted when the decay did not end at rest. */
  stop_px_s?: number | null;
}

/**
 * `GET /api/health`. Never calls `claude` or the LLM gateway.
 *
 * `interpreter` and `limits` are null for anonymous callers and for sessions with a
 * pending forced password change (PLAN-auth A12); `status`/`version`/`ffmpeg` are public.
 */
export interface Health {
  status: "ok";
  version: string;
  ffmpeg: boolean;
  interpreter: HealthInterpreter | null;
  limits: HealthLimits | null;
}

export interface HealthInterpreter {
  mode: InterpreterProvider;
  /** claude_cli: shutil.which(MIMIC_CLAUDE_BIN) is not None. openai_compat: MIMIC_LLM_BASE_URL + MIMIC_LLM_API_KEY + MIMIC_LLM_MODEL are configured (no network call). none: false. */
  available: boolean;
  model: string | null;
}

/** Upload limits the server enforces (from settings), so the client can pre-check them. */
export interface HealthLimits {
  max_upload_mb: number;
  max_duration_s: number;
  min_duration_s: number;
  /** Extra seconds tolerated over the maximum. */
  duration_tolerance_s: number;
}

/** Momentum after release, aggregated over `instances` inertia phases. */
export interface InertiaBehavior {
  model: InertiaModel;
  /** Set when model is exponential. */
  tau_ms: MeasuredNumber | null;
  /** Set when model is tween. */
  duration_ms: MeasuredNumber | null;
  /** Set when model is tween. */
  easing: Easing | null;
  release_speed_min_px_s: number;
  release_speed_max_px_s: number;
  instances: number;
  /** Exponential model: minimum speed at which the momentum stops (aggregated ExponentialFit.stop_px_s). Omitted when not observed. */
  stop_px_s?: MeasuredNumber | null;
}

export interface Interaction {
  type: InteractionType;
  type_source: TypeSource;
  type_confidence: Confidence;
  pattern: Pattern;
  target_element_id: string | null;
  target_label: string;
  target_description: string | null;
  trigger: Trigger;
  direction: Direction;
  total_duration_ms: TotalDuration;
}

/**
 * `POST /api/jobs/{id}/interpret` body. `use_interpreter` is required (no default): the
 * request itself is the user's explicit choice to send keyframes to the AI interpreter
 * (`true`) or to go back to heuristic labels (`false`).
 */
export interface InterpretRequest {
  use_interpreter: boolean;
}

/** Which Layer B provider produced labels/roles/structure and how it went. */
export interface Interpretation {
  provider: InterpreterProvider;
  model: string | null;
  status: InterpretationStatus;
  duration_ms: number | null;
}

/**
 * `POST /api/interpreter/check`: actively test the configured interpreter.
 *
 * `ok: false` is a normal 200 answer (with `error`). Probe fields are null when that probe
 * did not run (e.g. `supports_images` for `claude_cli` without a deep check).
 */
export interface InterpreterCheck {
  mode: InterpreterProvider;
  ok: boolean;
  latency_ms: number | null;
  model: string | null;
  /** openai_compat: the model id appears in GET /models. */
  model_listed: boolean | null;
  supports_images: boolean | null;
  /** Best structured-output mode that worked. */
  structured_output: "json_schema" | "json_object" | "prompt_only" | null;
  error: InterpreterCheckError | null;
  checked_at: string;
}

export interface InterpreterCheckError {
  code: "not_configured" | "unauthorized" | "unreachable" | "timeout" | "model_not_found" | "no_image_support" | "bad_response";
  /** Human-readable; never contains credentials. */
  message: string;
}

/** `POST /api/jobs` -> 202. */
export interface JobCreated {
  id: string;
  status: "queued";
  created_at: string;
}

/**
 * `GET /api/jobs`: newest first (`created_at` desc, `id` desc), keyset-paginated.
 *
 * Pass `next_cursor` back as `cursor` for the next page; null on the last page.
 */
export interface JobList {
  items: JobStatus[];
  next_cursor: string | null;
}

/** Upload form options echoed back. `use_interpreter` is opt-in (default off, PLAN P9). */
export interface JobOptions {
  pixel_ratio: PixelRatioOption;
  use_interpreter: boolean;
}

/** The account that uploaded a job. */
export interface JobOwner {
  id: string;
  username: string;
}

/** Probe summary; null until probing finished. */
export interface JobSource {
  filename: string;
  width: number;
  height: number;
  fps: number;
  duration_s: number;
}

/** Top-level job status: `queued -> processing -> succeeded | failed`. */
export type JobState = "queued" | "processing" | "succeeded" | "failed";

/**
 * `GET /api/jobs/{id}`. Poll until `status` is terminal.
 *
 * `error` is normally null unless `status` is `failed`. Exception: a `succeeded` job
 * whose interpretation re-run failed keeps its previous result and reports that failure here.
 * `owner` is null only for legacy jobs uploaded before accounts existed (admin-only).
 */
export interface JobStatus {
  id: string;
  status: JobState;
  stage: Stage;
  stage_label: string;
  progress: number;
  error: ErrorDetail | null;
  created_at: string;
  updated_at: string;
  source: JobSource | null;
  options: JobOptions;
  owner: JobOwner | null;
}

/** One PNG. `t_ms` is null for composite images (element crops). */
export interface KeyframeArtifact {
  name: string;
  kind: KeyframeKind;
  t_ms: number | null;
  /** Set for kind=element. */
  element_id: string | null;
  url: string;
}

/** `POST /api/auth/login` body. The username is stripped + lowercased server-side. */
export interface LoginRequest {
  username: string;
  password: string;
}

/**
 * Seamless-loop length of the autoplay content. Never guessed: `observed` is false when
 * the content did not repeat within the recording (`period_px`/`duration_ms` null).
 */
export interface LoopInfo {
  observed: boolean;
  /** Length of one content copy, CSS px. */
  period_px: MeasuredNumber | null;
  /** period_px / speed (stored so outputs can quote it, never recomputed). */
  duration_ms: MeasuredNumber | null;
}

/** `GET /api/auth/me`, `POST /api/auth/login`, `POST /api/auth/password`. */
export interface Me {
  id: string;
  username: string;
  role: UserRole;
  must_change_password: boolean;
  created_at: string;
}

/** A static (non-animated) solid colour estimate with its own confidence. */
export interface MeasuredColor {
  /** Uppercase #RRGGBB. */
  value: string;
  confidence: Confidence;
}

/** A static (non-animated) measurement with its own confidence. */
export interface MeasuredNumber {
  value: number;
  confidence: Confidence;
}

/** Static shadow estimate. `value: null` = none or very subtle. */
export interface MeasuredShadow {
  value: Shadow | null;
  confidence: Confidence;
}

export interface Meta {
  /** UTC timestamp set by the pipeline. */
  generated_at: string;
  pipeline_version: string;
  estimated: true;
  disclaimer: string;
}

/** A changed UI element. Children's transforms are relative to `parent_id`. */
export interface MotionElement {
  id: string;
  label: string;
  label_source: LabelSource;
  role: Role;
  parent_id: string | null;
  kind: ElementKind;
  /** Box in state A (initial). */
  bbox_initial: Box;
  /** Box in state B (active / open / pressed). */
  bbox_active: Box;
  text_like: boolean;
  static: ElementStatic;
}

/**
 * Root of the IR. Cross-references (element/segment/transition ids) are validated.
 *
 * `mode` selects the shape: `transition` (segments + transitions, PLAN §8) or
 * `continuous` (one scroller in `continuous`; no segments/transitions/relationships).
 */
export interface MotionSpec {
  schema_version: SchemaVersion;
  job_id: string;
  meta: Meta;
  mode: SpecMode;
  source: Source;
  scene?: Scene | null;
  interaction: Interaction;
  elements: MotionElement[];
  /** Transition mode: >= 1 segment. Continuous mode: empty. */
  segments: Segment[];
  transitions: Transition[];
  relationships: Relationship[];
  continuous?: ContinuousMotion | null;
  cursor: Cursor;
  structure: string[];
  interpretation: Interpretation;
  warnings: SpecWarning[];
  /** Element -> property -> value before the forward motion. */
  initial_state: Record<string, Partial<Record<Property, Value>>>;
  /** Element -> property -> value after the forward motion. */
  active_state: Record<string, Partial<Record<Property, Value>>>;
}

/**
 * The text tabs. Serialized keys: `technical`, `llm_prompt`, `css`, `json` and, in
 * continuous mode only, `js` (omitted when null, so transition outputs are unchanged).
 */
export interface Outputs {
  technical: string;
  llm_prompt: string;
  css: string;
  /** Pretty IR export without transition / continuous samples. */
  json: string;
  /** Suggested JS driver (continuous mode only; absent in transition mode). */
  js?: string | null;
}

/** Autoplay slows to a stop when the pointer hovers / presses (`on`). */
export interface PauseBehavior {
  on: PauseTrigger;
  on_confidence: Confidence;
  decel_ms: MeasuredNumber | null;
  easing: Easing | null;
  stops_completely: boolean;
}

/** One labelled stretch of the scroller's velocity profile (chronological, no overlap). */
export interface Phase {
  id: string;
  kind: PhaseKind;
  /** Milliseconds. */
  start_ms: number;
  /** Milliseconds. */
  end_ms: number;
  v_start_px_s: number;
  v_end_px_s: number;
  /** Signed velocity with the largest magnitude. */
  v_peak_px_s: number;
  displacement_px: number;
  fit: ConstantFit | ExponentialFit | RampFit | TweenFit | null;
  /** Cut short, e.g. decelerate cut by a drag, inertia re-grabbed. */
  interrupted: boolean;
  evidence: PhaseEvidence;
  /** Label confidence. */
  confidence: Confidence;
  notes: string[];
}

/** Length in CSS px (translate, height, border-radius). */
export interface PxValue {
  kind: "px";
  number: number;
}

/** Eased velocity ramp `v = from + (to - from) E((t - t0) / D)` (decelerate / resume). */
export interface RampFit {
  model: "ramp";
  from_px_s: number;
  to_px_s: number;
  duration_ms: MeasuredNumber;
  easing: Easing;
}

/** Unitless ratio (scale, opacity). */
export interface RatioValue {
  kind: "ratio";
  number: number;
}

/**
 * Timing relation between transitions of one segment (PLAN §6.9).
 *
 * `transition_ids[0]` is the reference (primary) transition. `offset_ms` is the start
 * offset of the others relative to it; `interval_ms` is the stagger step.
 */
export interface Relationship {
  kind: RelationshipKind;
  segment_id: SegmentId;
  transition_ids: string[];
  offset_ms: number | null;
  interval_ms: number | null;
}

/** `GET /api/jobs/{id}/result` and `data/jobs/<id>/result.json`. */
export interface ResultEnvelope {
  job_id: string;
  spec: MotionSpec;
  outputs: Outputs;
  artifacts: Artifacts;
}

export interface ResumeBehavior {
  delay_after_rest_ms: MeasuredNumber;
  delay_after_release_ms: MeasuredNumber | null;
  /** Hover pause: resume onset after the pointer left the scroller. Omitted when no pointer leave was seen before the resume. */
  delay_after_leave_ms?: MeasuredNumber | null;
  ramp_ms: MeasuredNumber;
  easing: Easing | null;
  to_speed_px_s: number;
  direction_preserved: boolean;
}

/** Recorded page context (PLAN-continuous §13). Optional; omitted when not measured. */
export interface Scene {
  /** Recorded frame size in CSS px. */
  viewport_css: Size;
  page_background?: MeasuredColor | null;
}

/**
 * An analysed motion window. `fwd`/`rt_in` are forward, `rev`/`rt_out` reverse.
 *
 * `start_ms`/`end_ms` = detected active run; `onset_ms`/`settle_ms` = earliest fitted
 * start / latest fitted end of its transitions; `trigger_event_ms` = cursor enter/click time.
 */
export interface Segment {
  id: SegmentId;
  kind: SegmentKind;
  /** Milliseconds. */
  start_ms: number;
  /** Milliseconds. */
  end_ms: number;
  /** Milliseconds. */
  onset_ms: number;
  /** Milliseconds. */
  settle_ms: number;
  trigger_event_ms: number | null;
}

/** One box-shadow layer: `{x}px {y}px {blur}px {spread}px rgba(r,g,b,a)`. */
export interface Shadow {
  x: number;
  y: number;
  blur: number;
  spread: number;
  rgba: [number, number, number, number];
}

/** Box shadow. `shadow: null` means `none` / not detectable. */
export interface ShadowValue {
  kind: "shadow";
  shadow: Shadow | null;
}

/** Width x height in CSS px. */
export interface Size {
  w: number;
  h: number;
}

/**
 * `grid`: rests land on the card pitch. `abrupt_ambiguous`: abrupt stops that may be a
 * snap or the pointer stopping before release (no grid evidence; from `stop` phases).
 */
export interface SnapBehavior {
  kind: SnapKind;
  step_px: MeasuredNumber | null;
  duration_ms: MeasuredNumber | null;
  easing: Easing | null;
  /** Spring-like overshoot seen; spring not reconstructed. */
  overshoot: boolean;
}

/** Input video facts. `width`/`height` are source pixels after rotation (not CSS px). */
export interface Source {
  filename: string;
  /** e.g. mp4, mov, webm (from ffprobe format). */
  container: string;
  /** e.g. h264, hevc, vp9. */
  codec: string;
  width: number;
  height: number;
  duration_ms: number;
  fps_nominal: number;
  fps_effective: number;
  is_vfr: boolean;
  pixel_ratio: PixelRatio;
  pixel_ratio_source: PixelRatioSource;
  /** Median frame interval, rounded. */
  timing_resolution_ms: number;
}

export interface Span {
  /** Milliseconds. */
  start_ms: number;
  /** Milliseconds. */
  end_ms: number;
}

export interface SpecWarning {
  code: WarningCode;
  severity: WarningSeverity;
  message: string;
}

/**
 * Pipeline stage. `done` is set together with `succeeded`.
 *
 * On failure the stage stays at the stage that failed, so the UI can say where.
 */
export type Stage = "queued" | "probing" | "preview" | "scanning" | "decoding" | "detecting_elements" | "measuring" | "fitting" | "interpreting" | "generating" | "done";

/**
 * `POST /api/admin/users` (201) and `.../reset-password` (200).
 *
 * `temporary_password` is shown once; the account must change it at next sign-in.
 */
export interface TemporaryPassword {
  user: AdminUser;
  temporary_password: string;
}

/** Opaque content description (`content` property; not measured geometrically). */
export interface TextValue {
  kind: "text";
  text: string;
}

/** `settle - onset` per direction; `reverse` is null when no reverse was recorded. */
export interface TotalDuration {
  forward: number;
  reverse: number | null;
}

/** One property animating on one element in one segment. */
export interface Transition {
  id: string;
  segment_id: SegmentId;
  element_id: string;
  property: Property;
  from: Value;
  to: Value;
  /** to - from for px/ratio values; null for color/shadow/text. */
  delta: number | null;
  /** Absolute video time of the fitted start (t0). */
  start_ms: number;
  /** start_ms - segment onset_ms. */
  delay_ms: number;
  duration_ms: number;
  easing: Easing;
  /** CSS transform-origin, e.g. "center", "top center". */
  transform_origin: string | null;
  confidence: TransitionConfidence;
  notes: string[];
  /** [t_ms, progress] pairs for timeline/debug. Excluded from the JSON export. */
  samples: [number, number][];
}

/** Per-transition confidences; `band` derives from `overall`. */
export interface TransitionConfidence {
  overall: number;
  value: number;
  timing: number;
  easing: number;
  band: ConfidenceBand;
}

export interface Trigger {
  kind: TriggerKind;
  reverse_kind: ReverseTriggerKind;
  description: string;
  confidence: Confidence;
}

/** Eased position tween `x = x0 + D E((t - t0) / T)` (snap, tween-style inertia). */
export interface TweenFit {
  model: "tween";
  /** Signed distance travelled. */
  distance_px: MeasuredNumber;
  duration_ms: MeasuredNumber;
  easing: Easing;
}

/** `PATCH /api/admin/users/{id}` body. At least one field must be set (non-null). */
export interface UpdateUserRequest {
  role?: UserRole | null;
  is_active?: boolean | null;
}

/* ---------- constants mirrored from the backend ---------- */

export const SCHEMA_VERSION = "0.2" as const;

/** Pipeline stages in execution order (core/stages.py). */
export const STAGE_ORDER: readonly Stage[] = ["queued", "probing", "preview", "scanning", "decoding", "detecting_elements", "measuring", "fitting", "interpreting", "generating", "done"];

/** UI label per stage (same text as JobStatus.stage_label). */
export const STAGE_LABELS: Record<Stage, string> = {
  "queued": "Waiting",
  "probing": "Reading video",
  "preview": "Preparing preview",
  "scanning": "Finding UI states",
  "decoding": "Extracting frames",
  "detecting_elements": "Detecting changed elements",
  "measuring": "Measuring motion",
  "fitting": "Estimating timing & easing",
  "interpreting": "Labeling elements (AI)",
  "generating": "Writing specification",
  "done": "Done",
};

/** Overall-progress window [start, end] per stage (core/stages.py). */
export const STAGE_WINDOWS: Record<Stage, readonly [number, number]> = {
  "queued": [0.0, 0.0],
  "probing": [0.0, 0.05],
  "preview": [0.05, 0.12],
  "scanning": [0.12, 0.3],
  "decoding": [0.3, 0.42],
  "detecting_elements": [0.42, 0.52],
  "measuring": [0.52, 0.72],
  "fitting": [0.72, 0.78],
  "interpreting": [0.78, 0.95],
  "generating": [0.95, 1.0],
  "done": [1.0, 1.0],
};

/** Value kind used by each property's from/to. */
export const PROPERTY_VALUE_KIND: Record<Property, Value["kind"]> = {
  "translateX": "px",
  "translateY": "px",
  "height": "px",
  "border-radius": "px",
  "scale": "ratio",
  "scaleX": "ratio",
  "scaleY": "ratio",
  "opacity": "ratio",
  "color": "color",
  "background-color": "color",
  "box-shadow": "shadow",
  "content": "text",
};

/** Confidence bands: high >= BAND_HIGH_MIN, medium >= BAND_MEDIUM_MIN, else low. */
export const BAND_HIGH_MIN = 0.8;
export const BAND_MEDIUM_MIN = 0.5;
/** Transitions with overall confidence below this are 'uncertain observations'. */
export const UNCERTAIN_BELOW = 0.3;

/** Continuous mode: phase kinds in grammar order (PLAN-continuous §4.5). */
export const PHASE_KINDS: readonly PhaseKind[] = ["autoplay", "decelerate", "paused", "drag", "inertia", "snap", "stop", "resume", "unknown"];
/** Max points in `ContinuousMotion.samples` ([t_ms, v_px_s, pos_px, quality]). */
export const CONTINUOUS_SAMPLE_MAX = 900;
/** Sign of every continuous-mode velocity / displacement. */
export const SIGN_CONVENTION = "positive = content moves right (x) / down (y)" as const;

/** Password length bounds (characters after NFKC normalization, app/auth/policy.py). */
export const PASSWORD_MIN_LENGTH = 12;
export const PASSWORD_MAX_LENGTH = 256;
/** Username rule (lowercase; app/auth/policy.py). Use with `new RegExp(...)`. */
export const USERNAME_PATTERN = "^[a-z0-9][a-z0-9._-]{2,31}$";
