"""Contract export: Pydantic models -> JSON Schema -> TypeScript (``make contract``).

Writes two generated files (never edit them by hand):

* ``docs/contract/motion-spec.schema.json`` — JSON Schema 2020-12 of the API + MotionSpec IR
  in *serialization* mode (what the browser receives). Root ``$ref`` = ``ResultEnvelope``.
* ``web/lib/types.ts`` — TypeScript mirror of that schema, plus a few constants that the
  frontend needs from the backend (stage order/labels, confidence band thresholds).

Usage::

    uv run python -m app.contract           # regenerate both files
    uv run python -m app.contract --check   # exit 1 if either file is stale

Output is deterministic: same models -> byte-identical files. ``tests/unit/test_ir_contract.py``
fails when the committed files are stale.
"""

from __future__ import annotations

import argparse
import json
import sys
import typing
from pathlib import Path
from typing import Any

from pydantic.json_schema import models_json_schema

from app.api import schemas as api_schemas
from app.config import REPO_ROOT
from app.core.stages import STAGE_LABELS, STAGE_ORDER, STAGE_WINDOWS
from app.models import ir

SCHEMA_PATH: Path = REPO_ROOT / "docs" / "contract" / "motion-spec.schema.json"
TYPES_PATH: Path = REPO_ROOT / "web" / "lib" / "types.ts"
SCHEMA_ID = "https://mimic.local/contract/motion-spec.schema.json"

#: Literal aliases hoisted to named TS types (inline enums with exactly these values, in this
#: order, render as the alias name). Order here = order in types.ts.
NAMED_LITERALS: tuple[tuple[str, Any], ...] = (
    ("InteractionType", ir.InteractionType),
    ("TypeSource", ir.TypeSource),
    ("Pattern", ir.Pattern),
    ("TriggerKind", ir.TriggerKind),
    ("ReverseTriggerKind", ir.ReverseTriggerKind),
    ("Direction", ir.Direction),
    ("ElementKind", ir.ElementKind),
    ("Role", ir.Role),
    ("LabelSource", ir.LabelSource),
    ("SegmentId", ir.SegmentId),
    ("SegmentKind", ir.SegmentKind),
    ("Property", ir.Property),
    ("CssEasingKeyword", ir.CssEasingKeyword),
    ("EasingFamily", ir.EasingFamily),
    ("ConfidenceBand", ir.ConfidenceBand),
    ("RelationshipKind", ir.RelationshipKind),
    ("CursorEventKind", ir.CursorEventKind),
    ("InterpreterProvider", ir.InterpreterProvider),
    ("InterpretationStatus", ir.InterpretationStatus),
    ("PixelRatio", ir.PixelRatio),
    ("PixelRatioSource", ir.PixelRatioSource),
    ("WarningSeverity", ir.WarningSeverity),
    ("WarningCode", ir.WarningCode),
    ("PixelRatioOption", api_schemas.PixelRatioOption),
    ("KeyframeKind", api_schemas.KeyframeKind),
)

#: The discriminated ``Value`` union is emitted as ``Value`` instead of inline.
VALUE_UNION_REFS = frozenset({"PxValue", "RatioValue", "ColorValue", "ShadowValue", "TextValue"})


# --------------------------------------------------------------------------------------------
# JSON Schema
# --------------------------------------------------------------------------------------------


def build_schema() -> dict[str, Any]:
    """JSON Schema for every contract model (serialization mode), defs sorted by name."""
    _, defs_doc = models_json_schema(
        [(m, "serialization") for m in api_schemas.CONTRACT_MODELS],
        ref_template="#/$defs/{model}",
    )
    defs = defs_doc["$defs"]
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": SCHEMA_ID,
        "title": "Mimic API + MotionSpec IR contract",
        "description": (
            "GENERATED by `make contract` from api/app (Pydantic). Do not edit. "
            "Root validates a ResultEnvelope; every API model is under $defs."
        ),
        "$ref": "#/$defs/ResultEnvelope",
        "$defs": {k: defs[k] for k in sorted(defs)},
    }


def schema_text(schema: dict[str, Any] | None = None) -> str:
    return json.dumps(schema or build_schema(), indent=2, ensure_ascii=False) + "\n"


# --------------------------------------------------------------------------------------------
# TypeScript
# --------------------------------------------------------------------------------------------


def _lit(v: Any) -> str:
    return json.dumps(v, ensure_ascii=False)


def _named_enum_index() -> dict[tuple[Any, ...], str]:
    index: dict[tuple[Any, ...], str] = {}
    for name, lit in NAMED_LITERALS:
        values = typing.get_args(lit)
        if values in index:
            raise ValueError(f"literal values of {name} collide with {index[values]}")
        index[values] = name
    return index


def _doc(text: str | None, indent: str = "") -> list[str]:
    if not text:
        return []
    text = text.replace("``", "`").strip()
    lines = [ln.rstrip() for ln in text.splitlines()]
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    return [f"{indent}/**"] + [f"{indent} * {ln}".rstrip() for ln in lines] + [f"{indent} */"]


def _wrap(t: str) -> str:
    return f"({t})" if (" | " in t or " & " in t) else t


class _TsRenderer:
    def __init__(self) -> None:
        self.enum_index = _named_enum_index()

    def type_of(self, node: dict[str, Any]) -> str:  # noqa: C901 - flat dispatch
        if "$ref" in node:
            return node["$ref"].rsplit("/", 1)[-1]
        if "const" in node:
            return _lit(node["const"])
        if "enum" in node:
            values = tuple(node["enum"])
            if values in self.enum_index:
                return self.enum_index[values]
            return " | ".join(_lit(v) for v in values)
        for key in ("oneOf", "anyOf"):
            if key in node:
                members = node[key]
                refs = {m.get("$ref", "").rsplit("/", 1)[-1] for m in members}
                if refs == VALUE_UNION_REFS:
                    return "Value"
                parts: list[str] = []
                for m in members:
                    t = self.type_of(m)
                    if t not in parts:
                        parts.append(t)
                return " | ".join(parts)
        typ = node.get("type")
        if isinstance(typ, list):
            return " | ".join(self.type_of({**node, "type": t}) for t in typ)
        if typ == "array":
            if "prefixItems" in node:
                return "[" + ", ".join(self.type_of(i) for i in node["prefixItems"]) + "]"
            return _wrap(self.type_of(node.get("items", {}))) + "[]"
        if typ == "object":
            if "properties" in node:
                return self.inline_object(node)
            ap = node.get("additionalProperties")
            value_t = self.type_of(ap) if isinstance(ap, dict) else "unknown"
            if "propertyNames" in node:
                return f"Partial<Record<{self.type_of(node['propertyNames'])}, {value_t}>>"
            return f"Record<string, {value_t}>"
        if typ in ("integer", "number"):
            return "number"
        if typ == "string":
            return "string"
        if typ == "boolean":
            return "boolean"
        if typ == "null":
            return "null"
        return "unknown"

    def fields(self, node: dict[str, Any], indent: str) -> list[str]:
        out: list[str] = []
        required = set(node.get("required", []))
        for name, prop in node.get("properties", {}).items():
            out += _doc(prop.get("description"), indent)
            key = name if name.isidentifier() else _lit(name)
            opt = "" if name in required else "?"
            out.append(f"{indent}{key}{opt}: {self.type_of(prop)};")
        return out

    def inline_object(self, node: dict[str, Any]) -> str:
        return "{ " + " ".join(self.fields(node, "")) + " }"

    def definition(self, name: str, node: dict[str, Any]) -> list[str]:
        lines = _doc(node.get("description"))
        if node.get("type") == "object" and "properties" in node:
            lines.append(f"export interface {name} {{")
            lines += self.fields(node, "  ")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {self.type_of(node)};")
        return lines


def render_ts(schema: dict[str, Any] | None = None) -> str:
    """Render ``web/lib/types.ts`` from the schema (+ backend constants)."""
    schema = schema or build_schema()
    r = _TsRenderer()
    out: list[str] = [
        "// GENERATED by `make contract` (api/app/contract.py) from",
        "// docs/contract/motion-spec.schema.json. DO NOT EDIT BY HAND.",
        "// Geometry is CSS px, times are integer ms, every value is an estimate.",
        "",
        "/* ---------- named literal types ---------- */",
        "",
    ]
    for name, lit in NAMED_LITERALS:
        out.append(
            f"export type {name} = " + " | ".join(_lit(v) for v in typing.get_args(lit)) + ";"
        )
    out += [
        "",
        "/** Animated value; `kind` is fixed per property (see PROPERTY_VALUE_KIND). */",
        "export type Value = " + " | ".join(sorted(VALUE_UNION_REFS, key=_value_order)) + ";",
        "",
        "/* ---------- models ---------- */",
        "",
    ]
    for name, node in schema["$defs"].items():
        out += r.definition(name, node)
        out.append("")
    out += _ts_constants()
    return "\n".join(out).rstrip() + "\n"


def _value_order(name: str) -> int:
    return ["PxValue", "RatioValue", "ColorValue", "ShadowValue", "TextValue"].index(name)


def _ts_constants() -> list[str]:
    stage_labels = ",\n".join(f"  {_lit(s.value)}: {_lit(STAGE_LABELS[s])}" for s in STAGE_ORDER)
    stage_windows = ",\n".join(
        f"  {_lit(s.value)}: [{STAGE_WINDOWS[s][0]}, {STAGE_WINDOWS[s][1]}]" for s in STAGE_ORDER
    )
    prop_kinds = ",\n".join(f"  {_lit(p)}: {_lit(k)}" for p, k in ir.PROPERTY_VALUE_KIND.items())
    return [
        "/* ---------- constants mirrored from the backend ---------- */",
        "",
        f"export const SCHEMA_VERSION = {_lit(ir.SCHEMA_VERSION)} as const;",
        "",
        "/** Pipeline stages in execution order (core/stages.py). */",
        "export const STAGE_ORDER: readonly Stage[] = ["
        + ", ".join(_lit(s.value) for s in STAGE_ORDER)
        + "];",
        "",
        "/** UI label per stage (same text as JobStatus.stage_label). */",
        f"export const STAGE_LABELS: Record<Stage, string> = {{\n{stage_labels},\n}};",
        "",
        "/** Overall-progress window [start, end] per stage (core/stages.py). */",
        "export const STAGE_WINDOWS: Record<Stage, readonly [number, number]> = "
        f"{{\n{stage_windows},\n}};",
        "",
        "/** Value kind used by each property's from/to. */",
        'export const PROPERTY_VALUE_KIND: Record<Property, Value["kind"]> = '
        f"{{\n{prop_kinds},\n}};",
        "",
        "/** Confidence bands: high >= BAND_HIGH_MIN, medium >= BAND_MEDIUM_MIN, else low. */",
        f"export const BAND_HIGH_MIN = {ir.BAND_HIGH_MIN};",
        f"export const BAND_MEDIUM_MIN = {ir.BAND_MEDIUM_MIN};",
        "/** Transitions with overall confidence below this are 'uncertain observations'. */",
        f"export const UNCERTAIN_BELOW = {ir.UNCERTAIN_BELOW};",
    ]


# --------------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------------


def generated_files() -> dict[Path, str]:
    schema = build_schema()
    return {SCHEMA_PATH: schema_text(schema), TYPES_PATH: render_ts(schema)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if files are stale")
    args = parser.parse_args(argv)
    stale: list[Path] = []
    for path, text in generated_files().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            print(f"up to date  {path.relative_to(REPO_ROOT)}")
            continue
        if args.check:
            stale.append(path)
            print(f"STALE       {path.relative_to(REPO_ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote       {path.relative_to(REPO_ROOT)}")
    if stale:
        print("Run `make contract` to regenerate.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
